name: 'Create UI Cloudfront + S3 Cloudformation Template'
description: 'Create UI Cloudfront + S3 Cloudformation Template'
author: 'net2phone'

inputs:
  name:
    description: 'The name of the project'
    required: true
  action:
    description: 'The action to perform (deploy or destroy)'
    required: true
  domain:
    description: 'The custom domain'
    required: false
  environment:
    description: 'The environment to deploy to'
    default: tmp
  optimized:
    description: 'Whether to optimize the build'
  variables:
    description: 'The environment variables'
    required: false
  aws-account:
    description: 'The AWS account to deploy to'
    required: true
  aws-region:
    description: 'The AWS region to deploy to'
    required: true
  aws-role-to-assume:
    description: 'The AWS role to assume'
    required: true
  aws-access-key-id:
    description: 'The AWS access key id'
    required: false
  aws-secret-access-key:
    description: 'The AWS secret access key'
    required: false
  aws-role-session-name:
    description: 'The AWS role session name'
    required: true
  aws-role-external-id:
    description: 'The AWS role external id'
    required: false
  aws-zone-id:
    description: 'The AWS zone id to deploy to'
    required: true
  aws-origin-access-identity:
    description: 'The AWS origin access identity to use'
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-external-id: ${{ inputs.aws-role-external-id }}
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-session-name: ${{ inputs.aws-role-session-name }}
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
    - name: Copy CDK to working directory
      shell: bash
      run: |
        mkdir cdk
        cp -r $GITHUB_ACTION_PATH/* ./cdk
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
        cache-dependency-path: ./cdk/yarn.lock
    - name: Create UI Cloudfront + S3 Cloudformation Template
      shell: bash
      run: $GITHUB_ACTION_PATH/script.sh
      env:
        AWS_ACCOUNT: ${{ inputs.aws-account }}
        AWS_REGION: ${{ inputs.aws-region }}
        AWS_ORIGIN_ACCESS_IDENTITY: ${{ inputs.identity }}
        AWS_ZONE_ID: ${{ inputs.aws-zone-id }}
        PROJECT_NAME: ${{ inputs.name }}
        DOMAIN: ${{ inputs.domain }}
        ENVIRONMENT: ${{ inputs.environment }}
        OPTIMIZED: ${{ inputs.optimized }}
        CDK_ACTION: ${{ inputs.action }}
        VARIABLES: ${{ inputs.variables }}
