name: 'Create UI Cloudfront + S3 Cloudformation Template'
description: 'Create UI Cloudfront + S3 Cloudformation Template'
author: 'net2phone'

inputs:
  name:
    description: 'The name of the project'
    required: true
  aws-account:
    description: 'The AWS account to deploy to'
    required: true
  aws-region:
    description: 'The AWS region to deploy to'
    required: true
  environment:
    description: 'The environment to deploy to'
    default: tmp
  variables:
    description: 'The variables to pass to the CDK'
  identity:
    description: 'The identity to use for the CDK'
  optimized:
    description: 'Whether to optimize the build'

outputs:
  stack:
    description: 'The name of the stack'

runs:
  using: node20
  main: './dist/index.js'
